# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=style
  - python: 3.6
    env: TOXENV=docs

addons:
  postgresql: "10.4"
  apt:
    sources:
    - heroku
    packages:
    - pandoc
    - enchant
    - heroku-toolbelt
    - redis-server
services:
  - redis-server

    # command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install --upgrade pip
  - pip install tox==3.1.2

before_script:
  - createuser dallinger --createdb
  - createdb -O dallinger dallinger
  - createdb -O dallinger dallinger-import
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  env:
    global:
    - DATABASE_URL=postgresql://dallinger@localhost/dallinger

# command to run tests, e.g. python setup.py test
script:
  - tox
